Added 'Orientation' parameter for vertical and horizontal layouts
bastibe/Violinplot-Matlab pull request #73
Opened 2024-07-02 11:49 UTC by fhaefele

![test_horizontal](https://github.com/bastibe/Violinplot-Matlab/assets/74400839/73a8032e-6aeb-4d39-a815-409e57b18b75)
![example](https://github.com/bastibe/Violinplot-Matlab/assets/74400839/c60ce474-b9a5-4636-9b0e-5aa9245507d2)
![example2](https://github.com/bastibe/Violinplot-Matlab/assets/74400839/2e8bf7fe-d30f-45c9-a292-2480a1a5fb06)

2024-07-03 07:02 UTC, bastibe requested changes
Thank you for the contribution! This is super useful!

However, I don't like the way the `plotOrientation` function makes the code harder to reason about in some places. I have sketched out an alternative structure that I'd prefer.

Nevertheless, great work, and thank you very much!

2024-07-03 07:02 UTC, bastibe commented on Violin.m
> +                    obj.HistogramPlot = plot(x,y,'-','LineWidth',1, 'Color', 'k');
This is referring to an earlier comment.

Here, the `case`s no longer plot, but merely prepare an `x` and `y`. This makes it harder to understand what's going on. I'd prefer the plot commands to still be inlined, as this is explicitly what the code does: It plots things. Preparing data is merely an ancillary complexity for the dual-orientation use case.

This is exacerbated by the name `plotOrientation`, which implies that the function actually plots. Which it doesn't. It merely swaps two variables.

I'd prefer a structure like this in every `case` instead:

```
x = [pos*ones(size(counts,2),1), pos+((counts')/max(counts))*max(jitterstrength)*2]';
y = [edges(1:end-1)+max(diff(edges))/2; edges(1:end-1)+max(diff(edges))/2];
[x, y] = obj.swapOrientationsMaybe(x, y);
obj.HistogramPlot = plot(x, y, '-', 'LineWidth', 1, 'Color', 'k');
```

Our first objective here is readability and maintainability!

2024-07-03 08:04 UTC, fhaefele commented on Violin.m
> +    properties (Hidden = true)
Sounds good. I will fix it.

2024-07-04 12:05 UTC, bastibe commented on Violin.m
> +                    obj.HistogramPlot = plot(x,y,'-','LineWidth',1, 'Color', 'k');
I would use the above function name `swapOrientationsMaybe`. But feel free to use a different name if you find one.

2024-07-04 13:08 UTC, fhaefele commented
Hm, merging and resolving conflicts is still pretty new to me. I gave it my best. Also I have addressed all of your comments. Let me know if everything fits now, else I will try to fix it asap. I was also thinking of including that 'parent' property which you discussed in the other PR.

2024-07-04 19:15 UTC, bastibe requested changes
This looks much better, thank you!

Just one more quick note: Could you format the code with spaces after operators (such as commas), so it matches the rest of the code?

Otherwise, this looks good to me!

2024-07-04 19:15 UTC, bastibe commented on Violin.m
> +        function [x,y] = swapOrientationMaybe(obj, x, y)
could you add a quick documentation to the function?

2024-07-06 19:29 UTC, fhaefele commented
Should be done and ready to merge. Do you want to also add the features from #24 ? Should be an easy inclusion.

2024-07-07 11:29 UTC, bastibe commented
> Do you want to also add the 'parent' property from https://github.com/bastibe/Violinplot-Matlab/pull/24 ?

That would be a good idea, thank you!

2024-07-08 09:22 UTC, fhaefele commented
I have added now the parent property and checked the functionality of the orientation swap and the 'parent' axis in a modified `testviolinplot.m`. To me it looks like it works fine.

2024-07-08 09:51 UTC, bastibe commented
Looks good to me! Thank you! 

If you want to, you could add an example to the README.

Is this ready to merge on your end?

2024-07-08 11:22 UTC, bastibe commented
I'll leave it up to you whether you want to add it to the README.

2024-07-12 08:02 UTC, fhaefele commented
I have edited the README and the `readme_figures.m` respectively. The README now shows a code snippet that can work on its own, which the previous one couldn't. I have also added two new test cases which test the 'Parent' and 'Orientation' property. Feel free to merge it into the main branch as you like.

2024-07-15 11:19 UTC, merged

2024-07-15 11:19 UTC, bastibe commented
Beautiful! Thank you!